//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalApp.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OperationEntity()
        {
            this.Medicines = new HashSet<MedicineEntity>();
        }
    
        public int Id { get; set; }
        public int TypeOperationId { get; set; }
        public int TreatmentId { get; set; }
    
        public virtual TypeOperationEntity TypeOperation { get; set; }
        public virtual TreatmentEntity Treatment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicineEntity> Medicines { get; set; }
    }
}
